[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.16.0", features = ["v4"] }
prost = "0.13.4"
tokio = { version = "1.43.0", features = ["full"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
