name: Pull Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Install Dependencies
        run: sudo apt-get update
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install cargo-deny
        uses: taiki-e/install-action@cargo-deny
      - name: Run deny check
        run: cargo deny check
      - name: Run Unit Tests
        run: cargo llvm-cov

