name: vulnerability_check

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Prerequesites
        run: cargo install cargo-audit
      - name: Run Vulnerability Check
        run: cargo audit

